# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
var_1: &cache_key v1-dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}-node-10.14

version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.14-browsers
        steps:
            - checkout
            - restore_cache:
                  key: *cache_key
            - run: npm ci
            - save_cache:
                  paths:
                      - ~/.npm
                      - ~/.cache/Cypress
                  key: *cache_key
            - run: npm run test:ci
            - run: bash <(curl -s https://codecov.io/bash)
            - store_test_results:
                  path: output
            - store_artifacts:
                  path: coverage/lcov.info
            - store_artifacts:
                  path: cypress/videos
            - store_artifacts:
                  path: cypress/screenshots
